/**
 * violation_engine.js
 * Analyzes attendance data and generates auto-violations.
 */

const ViolationEngine = (() => {
  const DB_KEY = 'kuk_violations_db';

  const RULES = {
    shift_start: '07:00',
    late_tolerance_mins: 5, // Toleransi sampai 07:05
    max_break_minutes: 60,  // Istirahat maks 60 menit
    flag_over_break: true,
    flag_missing_punch: true, // INCOMPLETE
    flag_unauthorized_absence: true // ABSENT (Mangkir)
  };

  function getViolations(unit = 'ALL') {
    const list = JSON.parse(localStorage.getItem(DB_KEY) || '[]');
    if (!unit || unit === 'ALL' || unit === 'semua') return list;
    const u = unit.toLowerCase().replace('kuk ', '');
    return list.filter(t => t.unit && t.unit.toLowerCase().includes(u));
  }

  function saveViolations(data) {
    localStorage.setItem(DB_KEY, JSON.stringify(data));
  }

  function generateTicketId() {
    return 'VIO-' + Date.now().toString().slice(-6) + '-' + Math.floor(Math.random()*1000);
  }

  /**
   * Scans a specific date and auto-generates violations with unit separation.
   * Prevents duplicates by checking existing ticket date+empId+rule.
   */
  function runDailyScan(dateStr, unit = 'ALL') {
    if (typeof AttendanceEngine === 'undefined') {
      throw new Error("AttendanceEngine not loaded");
    }

    const attendanceList = AttendanceEngine.getDailyAttendance(dateStr, unit);
    const existing = JSON.parse(localStorage.getItem(DB_KEY) || '[]');
    let newGenerated = 0;

    attendanceList.forEach(att => {
      // Ignore manually excused, off, cuti, izin, sakit
      if (att.status === 'EXCUSED' || att.status === 'OFF' || att.status === 'LEAVE' || att.status === 'SICK' || att.status === 'PERMISSION') return;

      let ruleBroken = null;
      let calculatedValue = '';

      const isFriday = new Date(dateStr).getDay() === 5;
      const shiftStartMin = isFriday ? (8 * 60) : (7 * 60);

      if (att.status === 'LATE') {
        ruleBroken = 'LATE_ARRIVAL';
        const [h, m] = (att.inTime || (isFriday ? '08:00' : '07:00')).split(':').map(Number);
        const inMins = h * 60 + m;
        const diffMins = inMins - shiftStartMin;
        calculatedValue = `Terlambat ${diffMins > 0 ? diffMins : 0} menit (Masuk: ${att.inTime || '-'}, Jadwal: ${isFriday ? '08:00' : '07:00'})`;
      } else if (att.isBreakExcess && RULES.flag_over_break) {
        ruleBroken = 'OVER_BREAK';
        calculatedValue = `Kelebihan istirahat ${att.breakExcessMinutes || 0} menit (Durasi: ${att.breakDuration || 0} mnt, ${att.breakOutTime || '-'}-${att.breakInTime || '-'})`;
      } else if (att.status === 'INCOMPLETE' && RULES.flag_missing_punch) {
        ruleBroken = 'MISSING_PUNCH';
        calculatedValue = `Hanya ada 1 scan (Jam: ${att.inTime || '-'})`;
      } else if (att.status === 'ABSENT' && RULES.flag_unauthorized_absence) {
        ruleBroken = 'UNAUTHORIZED_ABSENCE';
        calculatedValue = `Mangkir / Tidak Masuk (Tanpa Cuti/Izin Resmi)`;
      }

      if (ruleBroken) {
        // Check duplicate
        const isDup = existing.find(v => v.date === dateStr && v.employeeId === att.employeeId && v.ruleBroken === ruleBroken);
        if (!isDup) {
          const ticket = {
            id: generateTicketId(),
            source: 'SYSTEM',
            employeeId: att.employeeId,
            employeeName: att.employeeName,
            unit: att.unit || (att.employeeName && ['Nukul', 'Miftah'].includes(att.employeeName) ? 'KUK Palen' : 'KUK Bangunan'),
            date: dateStr,
            ruleBroken: ruleBroken,
            calculatedValue: calculatedValue,
            generatedTime: new Date().toISOString(),
            status: 'AUTO GENERATED',
            reviewer: null,
            history: [{
              state: 'AUTO GENERATED',
              timestamp: new Date().toISOString(),
              note: 'Generated by Violation Engine',
              actor: 'SYSTEM'
            }]
          };
          existing.push(ticket);
          newGenerated++;
        }
      }
    });

    if (newGenerated > 0) {
      saveViolations(existing);
    }

    return newGenerated;
  }

  /**
   * Transitions a ticket to a new state
   */
  function transitionTicket(ticketId, newState, note, reviewerName) {
    const existing = getViolations();
    const idx = existing.findIndex(v => v.id === ticketId);
    if (idx === -1) throw new Error("Ticket not found");

    const ticket = existing[idx];
    ticket.status = newState;
    ticket.reviewer = reviewerName;
    ticket.history.push({
      state: newState,
      timestamp: new Date().toISOString(),
      note: note,
      actor: reviewerName
    });

    existing[idx] = ticket;
    saveViolations(existing);
    return ticket;
  }

  return {
    RULES,
    getViolations,
    runDailyScan,
    transitionTicket
  };
})();

if (typeof window !== 'undefined') {
  window.ViolationEngine = ViolationEngine;
}
if (typeof module !== 'undefined' && module.exports) {
  module.exports = ViolationEngine;
}

