/**
 * violation_engine.js
 * Analyzes attendance data and generates auto-violations.
 */

const ViolationEngine = (() => {
  const DB_KEY = 'kuk_violations_db';

  const RULES = {
    late_tolerance_mins: 15,
    flag_missing_punch: true, // INCOMPLETE
    flag_unauthorized_absence: true, // ABSENT
    shift_start: '08:00'
  };

  function getViolations() {
    return JSON.parse(localStorage.getItem(DB_KEY) || '[]');
  }

  function saveViolations(data) {
    localStorage.setItem(DB_KEY, JSON.stringify(data));
  }

  function generateTicketId() {
    return 'VIO-' + Date.now().toString().slice(-6) + '-' + Math.floor(Math.random()*1000);
  }

  /**
   * Scans a specific date and auto-generates violations.
   * Prevents duplicates by checking existing ticket date+empId+rule.
   */
  function runDailyScan(dateStr) {
    if (typeof AttendanceEngine === 'undefined') {
      throw new Error("AttendanceEngine not loaded");
    }

    const attendanceList = AttendanceEngine.getDailyAttendance(dateStr);
    const existing = getViolations();
    let newGenerated = 0;

    attendanceList.forEach(att => {
      // Ignore manually excused or off
      if (att.status === 'EXCUSED' || att.status === 'OFF' || att.status === 'LEAVE' || att.status === 'SICK' || att.status === 'PERMISSION') return;

      let ruleBroken = null;
      let calculatedValue = '';

      if (att.status === 'LATE') {
        ruleBroken = 'LATE_ARRIVAL';
        // Calculate late duration
        const tIn = new Date(`2000-01-01T${att.inTime}`);
        const tStart = new Date(`2000-01-01T${RULES.shift_start}`);
        const diffMins = Math.floor((tIn - tStart) / 60000);
        calculatedValue = `Terlambat ${diffMins} menit (Masuk: ${att.inTime})`;
      } else if (att.status === 'INCOMPLETE' && RULES.flag_missing_punch) {
        ruleBroken = 'MISSING_PUNCH';
        calculatedValue = `Hanya ada 1 scan (Jam: ${att.inTime})`;
      } else if (att.status === 'ABSENT' && RULES.flag_unauthorized_absence) {
        ruleBroken = 'UNAUTHORIZED_ABSENCE';
        calculatedValue = `Mangkir (Tanpa Keterangan/Form)`;
      }

      if (ruleBroken) {
        // Check duplicate
        const isDup = existing.find(v => v.date === dateStr && v.employeeId === att.employeeId && v.ruleBroken === ruleBroken);
        if (!isDup) {
          const ticket = {
            id: generateTicketId(),
            source: 'SYSTEM',
            employeeId: att.employeeId,
            employeeName: att.employeeName,
            date: dateStr,
            ruleBroken: ruleBroken,
            calculatedValue: calculatedValue,
            generatedTime: new Date().toISOString(),
            status: 'AUTO GENERATED',
            reviewer: null,
            history: [{
              state: 'AUTO GENERATED',
              timestamp: new Date().toISOString(),
              note: 'Generated by Violation Engine',
              actor: 'SYSTEM'
            }]
          };
          existing.push(ticket);
          newGenerated++;
        }
      }
    });

    if (newGenerated > 0) {
      saveViolations(existing);
    }

    return newGenerated;
  }

  /**
   * Transitions a ticket to a new state
   */
  function transitionTicket(ticketId, newState, note, reviewerName) {
    const existing = getViolations();
    const idx = existing.findIndex(v => v.id === ticketId);
    if (idx === -1) throw new Error("Ticket not found");

    const ticket = existing[idx];
    ticket.status = newState;
    ticket.reviewer = reviewerName;
    ticket.history.push({
      state: newState,
      timestamp: new Date().toISOString(),
      note: note,
      actor: reviewerName
    });

    existing[idx] = ticket;
    saveViolations(existing);
    return ticket;
  }

  return {
    RULES,
    getViolations,
    runDailyScan,
    transitionTicket
  };
})();
